### ISSUE TITLE
Stereo not working with aframe update

### ISSUE THREAD

**Issue by aziliak** [oscarmarinmiro/aframe-stereo-component#28]
The component doesn't seem to be working with version 0.8.2.  Wanting confirmation on this issue.

<script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>

The only error I am seeing in the console is the following (not sure if related):

Error: WebGL warning: drawArrays: Active texture 0 for target 0x0de1 is 'incomplete', and will be rendered as RGBA(0,0,0,1), as per the GLES 2.0.24 $3.8.2: The dimensions of `level_base` are not all positive.

**Comment by Fieora** [comment]
Yupp, I ran into this issue as well, I was able to replace the a-entity elements with a-videosphere and give them the same properties, and it worked fine so far.

**Comment by esi-jwr** [comment]
Same for me, but the issue is upstream. Browser APIs / aframe no longer accept non-power-of-two dimensions with just a warning, instead it seems there has to be an explicit declaration. Comparing the code for a-videosphere gave me the right hints to get this working again. Plus a new parameter seems to control back/front face - which was a bug in aframe 0.8.0's video texture, breaking playback. 

Combined it just comes down to specifying the material for your stereo-separate assets with two new parameters (side, npot) like so:

aSphereLeft.setAttribute('material', "shader: flat; side: back; npot: true; src: #myVideoAsset");

See original change in a-frame:
https://github.com/aframevr/aframe/commit/5ead860379ebe61d2ef1f2acbe2eed5537ccc682

**Comment by aziliak** [comment]
@esi-jwr Sorry for the late response.  This resolved my issue!

Maybe something can be added to the documentation of this component regarding this? @oscarmarinmiro
